Optimized by removing curl from for loop.

diff --git a/pphgen b/pphgen
--- a/pphgen
+++ b/pphgen
@@ -1,18 +1,21 @@
 #!/bin/bash
 
 re='^[0-9]+$'
-j="$(expr ${1} - 1)"
 
 if ! [[ $1 =~ $re ]] ; then
-	echo "ERROR: Argument is not a number." >&2; exit 1
+	echo "ERROR: Argument is not a number." >&2
+	return 1
 fi
 
-for ((i=0;i<$1;i++))
+numbers="$(curl -s "https://www.random.org/integers/?num=${1}&min=1&max=1466238&col=${1}&base=10&format=html&rnd=new" | grep "=\"data\"" | sed 's/[^0-9\t]*//g')"
+
+read -a array <<< "$numbers"
+array_length=${#array[@]}
+
+for index in "${!array[@]}"
 do
-	n="$(curl -s "https://www.random.org/integers/?num=1&min=1&max=1466238&col=5&base=10&format=html&rnd=new" | grep "=\"data\"" | sed 's/[^0-9]*//g')"
-	p="$(head -${n} words | tail -1)"
-	if [[ $i -eq $j ]]
-	then
+	p="$(head -${array[$index]} words | tail -1)"
+	if [ $index -eq $((array_length-1)) ]; then
 		printf "$p\n"
 	else
 		printf "$p "
